sudo: required
services:
  - docker

before_install:
  - docker build -t husseinasoos/angular-app -f Dockerfile.dev .

script:
  - export NG_CLI_ANALYTICS=ci
  # - docker run husseinasoos/angular-app npm run test